version: "3"
services:
  springboot-app:
    container_name: springboot-app
    restart: on-failure
    depends_on:
      - mysqldb
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: passxxMysql
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  ./mysql/volume/:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: back
      MYSQL_ROOT_PASSWORD: passxxMysql